# Generated by Django 2.2.8 on 2020-05-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200505_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_idd',
            new_name='identity_number',
        ),
    ]
